name: tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: demo-42/.github/.github/workflows/reusable-tests.yml@main
